// all of routes are defined in here
export const HOME = '/'
export const MEMBERS = '/members'
export const TASKS = '/tasks'
export const TASKS_DETAIL = '/tasks/detail'
export const USER = '/user'
export const PASSWORD = '/password'
export const FORGET_PASSWORD = '/forgot-password'
export const CHANGE_PASSWORD = '/change-password'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const MEETINGS = '/meetings'
export const ORGANIZATION = '/organizations'

export const ADMIN = '/admin'
export const ADMIN_USERS = '/admin/users'
export const ADMIN_ORGANIZATIONS = '/admin/organizations'
export const ADMIN_GROUPS = '/admin/groups'
