// all of routes are defined in here
export const HOME = '/'
export const TASKS = '/tasks'
export const USER = '/user'
export const PASSWORD = '/password'
export const FORGET_PASSWORD = '/forgot-password'
export const CHANGE_PASSWORD = '/change-password'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const MEETINGS = '/meetings'
